### ISSUE TITLE
CR001 Nav Bar 

### ISSUE THREAD

**Issue by irdinasuhaidi** [IddJade/Debellani_Hijab#10]
Hi @ainamohd , can you please give me an update about the navigation bar design?

**Comment by ainamohd** [comment]
The navigation bar has been created and the design has been enhanced. Here is the snapshot of the navigation bar.
![Screenshot (61)](https://user-images.githubusercontent.com/80321418/117173801-b6cbb000-adff-11eb-8999-59a886d76a26.png)

**Comment by irdinasuhaidi** [comment]
noted, good job thanks!
