### ISSUE TITLE
Update on Change Request

### ISSUE THREAD

**Issue by irdinasuhaidi** [IddJade/Debellani_Hijab#7]

**Comment by irdinasuhaidi** [comment]
CR004 has been update

**Comment by ainamohd** [comment]
Noted

**Comment by fatimhzhrah** [comment]
@irdinasuhaidi can you please update the CR004 here?

**Comment by irdinasuhaidi** [comment]
![CR004](https://user-images.githubusercontent.com/65695010/117169970-2b045480-adfc-11eb-9ada-c3bf102ba1d1.jpg)
@fatimhzhrah here some snapshot of CR004

**Comment by fatimhzhrah** [comment]
@irdinasuhaidi alright thank you irdina

**Comment by irdinasuhaidi** [comment]
Alright, no big deal.
